//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CompanyEntities : DbContext
    {
        public CompanyEntities()
            : base("name=CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Dependent> Dependent { get; set; }
        public virtual DbSet<Dept_Locations> Dept_Locations { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Works_on> Works_on { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> usp_CreateDepartment(string dName, Nullable<decimal> mgrSSN)
        {
            var dNameParameter = dName != null ?
                new ObjectParameter("DName", dName) :
                new ObjectParameter("DName", typeof(string));
    
            var mgrSSNParameter = mgrSSN.HasValue ?
                new ObjectParameter("MgrSSN", mgrSSN) :
                new ObjectParameter("MgrSSN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_CreateDepartment", dNameParameter, mgrSSNParameter);
        }
    
        public virtual int usp_DeleteDepartment(Nullable<int> dNumber)
        {
            var dNumberParameter = dNumber.HasValue ?
                new ObjectParameter("DNumber", dNumber) :
                new ObjectParameter("DNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteDepartment", dNumberParameter);
        }
    
        public virtual ObjectResult<usp_GetAllDepartments_Result> usp_GetAllDepartments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllDepartments_Result>("usp_GetAllDepartments");
        }
    
        public virtual ObjectResult<usp_GetDepartment_Result> usp_GetDepartment(Nullable<int> dNumber)
        {
            var dNumberParameter = dNumber.HasValue ?
                new ObjectParameter("DNumber", dNumber) :
                new ObjectParameter("DNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDepartment_Result>("usp_GetDepartment", dNumberParameter);
        }
    
        public virtual int usp_UpdateDepartment(Nullable<int> dNumber, string dName)
        {
            var dNumberParameter = dNumber.HasValue ?
                new ObjectParameter("DNumber", dNumber) :
                new ObjectParameter("DNumber", typeof(int));
    
            var dNameParameter = dName != null ?
                new ObjectParameter("DName", dName) :
                new ObjectParameter("DName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateDepartment", dNumberParameter, dNameParameter);
        }
    
        public virtual int usp_UpdateDepartmentManager(Nullable<int> dNumber, Nullable<decimal> mgrSSN)
        {
            var dNumberParameter = dNumber.HasValue ?
                new ObjectParameter("DNumber", dNumber) :
                new ObjectParameter("DNumber", typeof(int));
    
            var mgrSSNParameter = mgrSSN.HasValue ?
                new ObjectParameter("MgrSSN", mgrSSN) :
                new ObjectParameter("MgrSSN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateDepartmentManager", dNumberParameter, mgrSSNParameter);
        }
    }
}
